### ISSUE TITLE
Añadir visualización de las reservas de los clientes y del admin

### ISSUE THREAD

**Issue by cris30158** [AlbeTroll/Java_PL2#10]

**Comment by cris30158** [comment]
La visualización de las reservas de cada cliente ya está, aunque hay que mejorar la parte gráfica y añadirlo en una ventana distinta a la del perfil del cliente

**Comment by cris30158** [comment]
Falta que se ordenen según fecha!!

**Comment by AlbeTroll** [comment]
No va a hacer falta, ya que se ordenan por inmueble, diría que es incluso mejor
