### ISSUE TITLE
Asignar los inmuebles a su correspondiente anfitrión

### ISSUE THREAD

**Issue by AlbeTroll** [AlbeTroll/Java_PL2#18]
Tenemos que realizar la vista "Mis inmuebles", podemos hacerlo como el admin los ve, así podemos reciclar código.

**Comment by AlbeTroll** [comment]
Y luego ya ahí, que el anfitrión pueda eliminar sus inmuebles si quiere

**Comment by cris30158** [comment]
Falta que el anfitrión pueda eliminar inmuebles porque hay que ver si comprobamos que no haya reservas "abiertas" o no

**Comment by AlbeTroll** [comment]
Está hecho
