### ISSUE TITLE
Issue #19: Posible fallo al cerrar sesión

### ISSUE THREAD

**Issue by AlbeTroll** [AlbeTroll/Java_PL2#19]
Cuando he estado probando todo lo relacionado con los filtros y la búsqueda, me ha dado la sensación de que al cerrar sesión como *Particular*, para iniciar sesión como *Anfitrión*, no me dejaba iniciar sesión, igual se queda un poco tostado la app.

**Comment by cris30158** [comment]
Lo he probado y no he tenido ningún problema. si te vuelve a pasar avísame y lo vemos

**Comment by AlbeTroll** [comment]
Tiene pinta de que era algo momentáneo 💯
