### ISSUE TITLE
Añadir búsqueda según una fecha

### ISSUE THREAD

**Issue by cris30158** [AlbeTroll/Java_PL2#23]
Además del botón de filtrar según precio... hay que seleccionar una fecha de entrada y salida y enseñar solo los disponibles para esas fechas (aunque luego al reservar puedas cambiarlas), y los filtros se harán sobre la lista de disponibles

**Comment by AlbeTroll** [comment]
Esto sí que falta hacerlo, esta medio implementado, pero da algún problema, lo hago yo si quieres.

**Comment by AlbeTroll** [comment]
Me equivoqué de botón JAJAJAJ

**Comment by AlbeTroll** [comment]
¡Hecho!
