### ISSUE TITLE
Problemas con las reservas

### ISSUE THREAD

**Issue by AlbeTroll** [AlbeTroll/Java_PL2#36]
Hay un problemón con las reservas.
Al eliminar el usuario todo genial, se borran las reservas que tenía asignadas. El problema es al borrar el inmueble, al no estar la sesión del usuario activa no se actualizan las reservas, y al abrir de nuevo la aplicación las reservas NO se borran, aunque el inmueble esté borrado.
Habrá que juntar los dos arrays de reservas o algo parecido, porque ahora mismo no hace ni caso.

**Comment by cris30158** [comment]
Solucionado

**Comment by AlbeTroll** [comment]
Ya funciona perfectamente, #39
